### ISSUE TITLE
Having trouble running on Windows

### ISSUE THREAD

**Issue by switchbl4de** [Verivox/lighthouse-monitor#17]
Getting a 
```
npm run server

> lightmon@2.4.0 server C:\Users\fpsbi\Documents\lighthouse-monitor
> cross-env DEBUG=${DEBUG:-LIGHTMON*} ./bin/server

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\fpsbi\Documents\lighthouse-monitor\bin\sync-cache ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\fpsbi\\Documents\\lighthouse-monitor\\bin\\sync-cache',
  path: 'C:\\Users\\fpsbi\\Documents\\lighthouse-monitor\\bin\\sync-cache',
  spawnargs: [
    '--report-dir',
    'C:\\Users\\fpsbi\\AppData\\Local\\Temp\\lightmon',
    '--verbose'
  ]
}
```

In reports.js when I comment this block out it runs (but doesn't run a report or let me pick date. Just shows up at localhost:3000):

```
    _setupCacheSync(dir = this._baseDir) {
        this._watcher = spawn(path.join(__dirname, '..', 'bin', 'sync-cache'), ['--report-dir', dir, '--verbose'], {
            detached: false,
            stdio: ['pipe', 'inherit', 'inherit']
        })
        //this._watcher.stdout.on('data', (data) => debug('LIGHTMON:SYNC:INFO')(`${data.trim()}`))
        //this._watcher.stderr.on('data', (data) => debug('LIGHTMON:SYNC:ERROR')(`${data.trim()}`))
        this._watcher.on('close', (code) => {
            debug('LIGHTMON:WARNING')(`Sync childprocess exited with code ${code}`)
            if (this._watcherRestarts > 3) {
                throw new Error('I would have to restart the sync process for more than 3 times, something is wrong. Exiting.')
            }
            if (this._shouldRestartCacheSync) {
                this._watcherRestarts++
                debug('LIGHTMON:WARNING')('Restarting cache sync process...')
                this._setupCacheSync(dir)
            } else {
                debug('LIGHTMON:WARNING')('shouldRestartCacheSync is false - not restarting sync process.')
            }
        })
    }
```

**Comment by LarsKumbier** [comment]
Hi Billy,
thanks for reporting. I forgot that windows does require the interpreter while spawning.
Could you check if this branch solves the issue? https://github.com/Verivox/lighthouse-monitor/tree/bug/17-spawn-windows

**Comment by switchbl4de** [comment]
That branch is working for me on Windows! Thank you. I even deployed this on a Digital Ocean node and working great

**Comment by LarsKumbier** [comment]
pleasure to help!

I'd be very interested in some external views from outside Verivox - could you drop a few lines on how you're using lightmon and what your experience is so far to my mailaddress? That'd be awesome!
